### ISSUE TITLE
The download process immediately stops even though there are no videos downloaded yet

### ISSUE THREAD

**Issue by HexaCodeX** [fiandev/otaku-downloader#12]
I don't know why, when after I choose resolution and episode list, script is force stoped, Haven't downloaded anything yet though 😐.

**Comment by fiandev** [comment]
I'm sorry about that, I think it's because the download link for the anime isn't available or the download method or resolution is not available

**Comment by fiandev** [comment]
I will try to add a download method and provide a condition if the download link does not exist or is not available.
